app:
  discord:
    token: ""
    prefix: "!"
    max-attachment-size: 8388608
  video:
    cache:
      path: "/videos"
      ttl: "1800"
      cron: "* */1 * * * ?"
  youtube:
    download:
      quality: "480p"
      overwrite: true
quarkus:
  banner:
    enabled: false
